theme: jekyll-theme-cayman
logo: https://images.unsplash.com/photo-1515555585025-54136276b6e3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80
title: "Jason's Intro to Bioinformatics"
