---
title: "Class09"
author: "Jason Baer"
date: "10/30/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
wisc.df <- read.csv("WisconsinCancer.csv")
```

Here we examine data from `r nrow(wisc.df)` patient samples.

```{r}
x <- table(wisc.df$diagnosis)
x
```


In this data-set we have `r x["M"]`  cancer and `r x["B"]` noncancer patients.

```{r}
length(grep(pattern = "_mean", x = colnames(wisc.df)))
```

```{r}
class(wisc.df)
```

```{r}
wisc.data <- as.matrix(wisc.df[, 3:32])
```


```{r}
row.names(wisc.data) <- wisc.df$id
```

```{r}
diagnosis <- wisc.df$diagnosis

```

```{r}
colMeans(wisc.data)
```
```{r}
apply(wisc.data,2,sd)

```


```{r}
round( apply(wisc.data, 2, sd), 3)
```

```{r}
#Perform PCA on wisc.data by completing the following code
wisc.pr <- prcomp (wisc.data, scale = TRUE)

summary(wisc.pr)
```

```{r}
biplot(wisc.pr)
```

```{r}
#produce a PCA plot with color for 1 and 2
plot(wisc.pr$x[,1], wisc.pr$x[,2], col = wisc.df$diagnosis, 
     xlab = "PC1", ylab = "PC3")
```

```{r}
#produce a PCA plot with color for 1 and 3
plot(wisc.pr$x[,1], wisc.pr$x[,3], col = wisc.df$diagnosis, 
     xlab = "PC1", ylab = "PC2")
```

```{r}
pr.var <- wisc.pr$sdev^2
head(pr.var)
```

```{r}
pve <- pr.var / (sum(pr.var))
head(pve)
```

```{r}
plot(pve, xlab = "Principal Component", ylab = "Proportion of Variance Explained", ylim = c(0,1), type = "o")
```

```{r}
barplot(pve, ylab = "Precent of Variance Explained",
     names.arg= paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )
```


```{r, eval = FALSE}
library("factoextra")
fviz_eig(wisc.pr, addlabels = TRUE)
```


```{r}
x <- summary(wisc.pr)
```

```{r}
x$importance[,"PC1"]
```

The first PC captures `r x$importance[2,"PC1"] *100` of the original variance in the dataset

```{r}
which(x$importance[3,] > 0.7)[1]
```

```{r}
wisc.pr$rotation["radius_mean", 1]
```

```{r}
wisc.pr$rotation["smoothness_se", 1]
```
```{r}
sort( abs(wisc.pr$rotation[,1]), decreasing = TRUE )
```


```{r}
data.scaled <- scale(wisc.data)
```

```{r}
data.dist <- dist(data.scaled)
head(data.dist)
```

```{r}
wisc.hclust <- hclust(data.dist, dist(wisc.pr$x[,1:3]))

```

